repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '2.1'  # add version here
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
-   repo: https://github.com/psf/black
    rev: 22.6
    hooks:
      - id: black